version: '3'

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: BBB_PHP
    depends_on:
      - db
    ports:
      - 8100:80
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:latest
    container_name: BBB_DB
    environment:
      MYSQL_DATABASE: BBB_DB
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '6100:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: BBB_phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8101:80

  composer:
    image: composer/composer
    command: update
    volumes:
      - ./:/app

volumes:
  db: { }