version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:8-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8080 -t public
        environment:
            docker: "true"
        ports:
            - 8100:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs

    composer:
        image: composer/composer
        command: update
        volumes:
            - ./:/app