version: '3'

services:
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: web
    depends_on:
      - db
    ports:
      - 8099:80
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: test_db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '6033:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-problem
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8055:80

  composer:
    image: composer/composer
    command: update
    volumes:
      - ./:/app

volumes:
  db: { }