<?php

namespace App\Exception;

class NotFoundModeratorException extends BaseException
{
    public function getException()
    {
        $this->exceptionName = NotFoundModeratorException::class;
        return parent::getException(); // TODO: Change the autogenerated stub
    }
}