<?php

namespace App\Exception;


class NotFoundMeetingCollectionException extends BaseException
{
    public function getException()
    {
        $this->exceptionName = NotFoundMeetingCollectionException::class;
        return parent::getException(); // TODO: Change the autogenerated stub
    }
}