<?php

namespace App\Exception;

class NotFoundAttendeeException extends BaseException
{
    public function getException()
    {
        $this->exceptionName = NotFoundAttendeeException::class;
        return parent::getException(); // TODO: Change the autogenerated stub
    }
}